name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GitHub token
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Setup Git
        run: |
          git config --global user.email "shreekarb5@gmail.com"
          git config --global user.name "Shreek1009"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://bshreekara.blogspot.com/feeds/posts/default'
